#!/bin/sh
#
# Build flpsed
#
set -euf
pkgname=flpsed
pkgver=0.7.3

[ x"${BUILD_TYPE:-void}" != x"void" ] && exit 0
pkgfile=$pkgname-$pkgver-void.bin.tar.gz

if [ ! -f src/$pkgname/$pkgname-$pkgver.tar.gz ] ; then
  echo "Missing pkg source"
  exit 1
fi

build_dir=$(pwd)/tmp
local_dir=/usr/local/pkgs/$pkgname-$pkgver
root_dir=$build_dir/$pkgname-root

tar -C $build_dir -zxf src/$pkgname/$pkgname-$pkgver.tar.gz

(
  cd $build_dir/$pkgname-$pkgver
  mkdir -p $root_dir$local_dir
  ./configure --prefix=$local_dir
  make
  make DESTDIR=$root_dir install
  # These need to be installed manually
  for file in \
	share/applications/flpsed.desktop \
	share/icons/hicolor/256x256/apps/flpsed.svg \
	share/icons/hicolor/scalable/apps/flpsed.png
  do
    install -D "$(basename "$file")" $root_dir$local_dir/$file
  done
)
tar -C $root_dir  -zcf $pkgfile $(echo $local_dir | sed -e 's!^/*!!')
echo $pkgfile >> artifacts.txt

