#!/bin/sh
#
# Build tinyserial
#
set -euf
pkgname=icecream
[ x"${BUILD_TYPE:-void}" != x"void" ] && exit 0

echo "========================== ICECREAM:START  ========================="

echo -y | env XBPS_ARCH=x86_64-musl xbps-install -y -A python3-pip
pip install --break-system-packages icecream
pip show icecream
srcpath=$(python3 -c "import icecream,os; print(os.path.dirname(icecream.__file__))")
pkgver=$(python3 -c "import icecream; print(icecream.__version__)")
pkgfile=$pkgname-$pkgver-void.bin.tar.gz

build_dir=$(pwd)/tmp
local_dir=/usr/local/pkgs/$pkgname-$pkgver
root_dir=$build_dir/$pkgname-root

mkdir -vp "$root_dir$(dirname "$local_dir")"
cp -av "$srcpath" "$root_dir$local_dir"
mkdir -vp "$root_dir$(dirname "$srcpath")"
ln -sf "$local_dir" "$build_dir$srcpath"

echo "========================== ICECREAM:DONE  ========================="
tar -C $root_dir  -zcf $pkgfile usr
echo $pkgfile >> artifacts.txt

