#!/bin/sh
#
# Build custom geany plugins
#
set -euf
pkgname=my-geany-plugins
pkgver=1.0

[ x"${BUILD_TYPE:-void}" != x"void" ] && exit 0
pkgfile=$pkgname-$pkgver-void.bin.tar.gz

build_dir=$(pwd)/tmp
local_dir=/usr/local/pkgs/$pkgname-$pkgver
root_dir=$build_dir/$pkgname-root

apps="
  https://github.com/leifmariposa/geany-ctrl-tab-plugin
  https://github.com/leifmariposa/geany-switch-document-plugin
  https://github.com/TortugaLabs/geany-macro-recorder-plugin
  https://github.com/TortugaLabs/geany-winsplit-plugin
"

mkdir -pv "$root_dir/$pkgname-$pkgver$local_dir/lib/geany"
mkdir -pv "$build_dir/$pkgname-$pkgver"
(
  cd $build_dir/$pkgname-$pkgver
  mkdir -p $root_dir$local_dir

  # Compile from github...
  for gitrepo in $apps
  do
    repodir=$(basename "$gitrepo")
    git clone "$gitrepo" "$repodir"
    (
      cd "$repodir" || exit 1
      make
      ls -l "$root_dir$local_dir"
      make install BINDIR="$root_dir$local_dir"'/lib/geany/$(LIBRARY)'
    ) || exit 1
  done
)
tar -C $root_dir  -zcf $pkgfile $(echo $local_dir | sed -e 's!^/*!!')
echo $pkgfile >> artifacts.txt

