#!/bin/sh
#
# Build pdfarranger
#
set -euf
pkgname=pdfarranger
pkgver=1.9.2

[ x"${BUILD_TYPE:-void}" != x"void" ] && exit 0
pkgfile=$pkgname-$pkgver-void.bin.tar.gz

if [ ! -f src/$pkgname/$pkgname-$pkgver.tar.gz ] ; then
  echo "Missing pkg source"
  exit 1
fi

build_dir=$(pwd)/tmp
local_dir=/usr/local/pkgs/$pkgname-$pkgver
root_dir=$build_dir/$pkgname-root

tar -C $build_dir -zxf src/$pkgname/$pkgname-$pkgver.tar.gz

(
  cd $build_dir
  mkdir -p $root_dir$local_dir
  cp -av $pkgname-$pkgver $root_dir$local_dir/dist

  #~ python3 -m venv --system-site-packages $root_dir$local_dir/venv
  #~ . $root_dir$local_dir/venv/bin/activate

  mkdir -p $root_dir$local_dir/bin
  cat >$root_dir$local_dir/bin/$pkgname <<-_EOF_
	#!/bin/sh
	quit=false
	for dep in python3-pikepdf
	do
	  xbps-query "\$dep" >/dev/null && continue
	  echo "Missing dependancy: \$dep" 1>&2
	  quit=true
	done
	\$quit && exit 1
	export PYTHONPATH=$local_dir/dist:\${PYTHONPATH:-}
	exec python -m $pkgname "\$@"
	_EOF_
  chmod 755 $root_dir$local_dir/bin/$pkgname
)
tar -C $root_dir  -zcf $pkgfile $(echo $local_dir | sed -e 's!^/*!!')
echo $pkgfile >> artifacts.txt

