#!/bin/sh
#
# Build svgbob
#
# Based on https://git.alpinelinux.org/aports/tree/testing/svgbob/APKBUILD
#
set -euf
pkgname=svgbob
pkgver=0.7.2

[ x"${BUILD_TYPE:-void}" != x"void" ] && exit 0
pkgfile=$pkgname-$pkgver-void.bin.tar.gz

if [ ! -f src/$pkgname/$pkgname-$pkgver.tar.gz ] ; then
  echo "Missing pkg source"
  exit 1
fi

build_dir=$(pwd)/tmp
local_dir=/usr/local/pkgs/$pkgname-$pkgver
root_dir=$build_dir/$pkgname-root

tar -C $build_dir -zxf src/$pkgname/$pkgname-$pkgver.tar.gz

(
  cd $build_dir/$pkgname-$pkgver
  mkdir -p $root_dir$local_dir
  set -x
  cargo fetch #--locked
  cargo build --frozen --release
  install -Dm0755 target/release/svgbob_cli "$root_dir$local_dir/bin/svgbob"
)
tar -C $root_dir  -zcf $pkgfile $(echo $local_dir | sed -e 's!^/*!!')
echo $pkgfile >> artifacts.txt

