#!/bin/sh
#
# Build tinyserial
#
set -euf
pkgname=tinyserial
pkgver=20090305.local1

[ x"${BUILD_TYPE:-void}" != x"void" ] && exit 0
pkgfile=$pkgname-$pkgver-void.bin.tar.gz

build_dir=$(pwd)/tmp
local_dir=/usr/local/pkgs/$pkgname-$pkgver
root_dir=$build_dir/$pkgname-root

(
  cd src/$pkgname
  make default
  mkdir -p $root_dir$local_dir/bin
  cp -av com $root_dir$local_dir/bin/com
)
tar -C $root_dir  -zcf $pkgfile $(echo $local_dir | sed -e 's!^/*!!')
echo $pkgfile >> artifacts.txt

