#!/bin/sh
#
# Build tktray and the xconso
#
set -euf
pkgname=tktray
pkgver=1.3.9

[ x"${BUILD_TYPE:-void}" != x"void" ] && exit 0
pkgfile=$pkgname-$pkgver-void.bin.tar.gz
tarball=src/$pkgname/TKTRAY-REL-$(echo $pkgver|tr . -).tar.gz
if [ ! -f $tarball ] ; then
  echo "Missing pkg source"
  exit 1
fi

build_dir=$(pwd)/tmp
local_dir=/usr/local/pkgs/$pkgname-$pkgver
root_dir=$build_dir/$pkgname-root

mkdir -p $build_dir
tar -C $build_dir -zxf $tarball

(
  cd $build_dir/tktray-TKTRAY-REL-$(echo $pkgver|tr . -)
  mkdir -p $root_dir$local_dir

  ./configure --prefix=$local_dir --libdir=$local_dir/lib
  make
  make DESTDIR=$root_dir install
  [ -d $root_dir/usr/bin ] && rmdir $root_dir/usr/bin || :

  mkdir -p $root_dir$local_dir/{bin,pixmaps}
)
icon=log-24x24.png
cp -av src/$pkgname/$icon $root_dir$local_dir/pixmaps
sed	-e "s|<sofile>|$local_dir/lib/$pkgname$pkgver/lib$pkgname$pkgver.so|" \
	-e "s|<icon>|$local_dir/pixmaps/$icon|" \
	< src/$pkgname/xconsole-helper.tk > $root_dir$local_dir/bin/xconsole-helper
chmod 755 $root_dir$local_dir/bin/xconsole-helper

tar -C $root_dir  -zcf $pkgfile $(echo $local_dir | sed -e 's!^/*!!')
echo $pkgfile >> artifacts.txt
