#!/bin/sh
#
# Build robodoc
#
set -euf
pkgname=robodoc
pkgver=4.99.44

[ x"${BUILD_TYPE:-void}" != x"void" ] && exit 0
pkgfile=$pkgname-$pkgver-void.bin.tar.gz

if [ ! -f src/$pkgname/$pkgname-$pkgver.tar.gz ] ; then
  echo "Missing pkg source"
  exit 1
fi

build_dir=$(pwd)/tmp
local_dir=/usr/local/pkgs/$pkgname-$pkgver
root_dir=$build_dir/$pkgname-root

tar -C $build_dir -zxf src/$pkgname/$pkgname-$pkgver.tar.gz

(
  cd $build_dir/$pkgname-$pkgver
  mkdir -p $root_dir$local_dir
  mkdir -p Source/sys
  echo '#include <unistd.h>' > Source/sys/unistd.h
  ./configure --prefix=$local_dir
  make
  make DESTDIR=$root_dir install
)
tar -C $root_dir  -zcf $pkgfile $(echo $local_dir | sed -e 's!^/*!!')
echo $pkgfile >> artifacts.txt
