#!/bin/sh
#
# Build xpac
#
set -euf
pkgname=xpad
pkgver=5.8.0

[ x"${BUILD_TYPE:-void}" != x"void" ] && exit 0
pkgfile=$pkgname-$pkgver-void.bin.tar.gz

if [ ! -f src/$pkgname/$pkgname-$pkgver.tar.bz2 ] ; then
  echo "Missing pkg source"
  exit 1
fi

build_dir=$(pwd)/tmp
local_dir=/usr/local/pkgs/$pkgname-$pkgver
root_dir=$build_dir/$pkgname-root

tar -C $build_dir -jxf src/$pkgname/$pkgname-$pkgver.tar.bz2
src=$(pwd)/src/$pkgname
(
  cd $build_dir/$pkgname-$pkgver
  mkdir -p $root_dir$local_dir
  ( cd data ; patch < $src/xpad.desktop.dif )
  ./autogen.sh
  ./configure --prefix=$local_dir --bindir=$local_dir/libexec
  make
  make DESTDIR=$root_dir install

  # Make it so it is self-contained...
  ( cd $root_dir$local_dir/libexec || exit 1
    for j in $(ldd xpad | awk '{print $3}')
    do
      cp "$j" .
    done
  )
  mkdir -p $root_dir$local_dir/bin
  ( tee $root_dir$local_dir/bin/xpad | md5sum ) <<-_EOF_
	#!/bin/sh
	export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:$local_dir/libexec
	exec $local_dir/libexec/xpad "\$@"
	_EOF_
  chmod 755 $root_dir$local_dir/bin/xpad
)
tar -C $root_dir  -zcf $pkgfile $(echo $local_dir | sed -e 's!^/*!!')
echo $pkgfile >> artifacts.txt
